// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtfviplybpkzphuxgdav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0ZnZpcGx5YnBrenBodXhnZGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTMzOTAsImV4cCI6MjA1NTE4OTM5MH0.PBn6DES_gmZbkXceAt5s-gdd4Lbv8oFu_I13PxB_o5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);